<?php

namespace Database\Seeders;

use App\Models\Candidato;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CandidatoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        $candidatos = [
            [
                'nombre' => 'Ricardo Velásquez Ramirez',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 42,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Juan Carlos Merino',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Keiko Fujimori',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Rafael López Aliaga',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 41,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Alex González',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 18,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Alfonso López Chau',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 2,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Álvaro Paz de la Barra',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 6,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Aurelio Pastor',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 12,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Arturo Fernández Bazán',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 43,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos Alvarez',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 23,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos Anderson',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 37,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos Espá',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 35,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos Neuhaus',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos Morales Andrade',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 40,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'César Acuña',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 3,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Charlie Carrasco',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 17,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Eduardo Liu Palacios',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 29,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Francisco Sagasti',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 22,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Fernando Olivera',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 21,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Herbert Caller',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 24,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Jose Luna Galvez',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 38,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Phillip Butters',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 4,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Rafael Belaunde Llosa',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 10,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Yonhy Lescano',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 25,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Zosimo Cardenas Muje',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 5,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            // ALCALDIA  PROVINCIAL LIMA
            [
                'nombre' => 'Ulises Villegas',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 20,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Aron Espinoza',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 38,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Elizabeth León',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 21,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Francis Allison',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 4,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Jorge Ugarte',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 18,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Luis Enrique Gálvez',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Renzo Reggiardo',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 41,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Richard Acuña',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 3,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            // ALCALDIA  DISTRITAL SJL
            [
                'nombre' => 'Hector Alejandro Bustamante',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => null,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Jacobo Vaisman',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 6,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Americo Zegarra',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 41,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Flor Hurtado',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 18,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos Diaz',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 37,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Edwin Mejia Cerdan',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 2,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            // ALCALDIA  DISTRITAL LA VICTORIA
            [
                'nombre' => 'Joaquín Reynaldo Albarracín',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 3,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Matita Rosas',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 21,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Joe Zanabria Soberon',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 4,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Claudia Torres',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 33,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Jesús Samaniego',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 41,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            // GOBIERNO REGIONAL AYACUCHO
            [
                'nombre' => 'Juan Carlos Arango',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 30,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Mario Carhuapoma',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 20,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Pabel Bellido',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 10,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Renol Pichardo',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 38,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //VICEPRESIDENTE FUERZA POPULAR
            [
                'nombre' => 'Luis Galarreta Velarde',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Patricia Juárez Gallegos',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //DIPUTADO FUERZA POPULAR
            [
                'nombre' => 'Hernando Guerra Garcia Campos',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Carmen Patricia Juarez Gallegos',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos Ernesto Bustamante Donayre',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //SENADO FUERZA POPULAR
            [
                'nombre' => 'Fernando Miguel Rospigliosi Capurro',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Rosangella Andrea Barbaran Reyes',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Luis Enrique Otoya Trelles',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //PARLAMENTO ANDINO FUERZA POPULAR
            [
                'nombre' => 'Luis Fernando Galarreta Velarde',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Anakaren Sofia Aguilar Terrones',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Jaime Agustin Sobero Taira',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //SENADO FUERZA POPULAR AMAZONAS
            [
                'nombre' => 'Mery Eliana Infantes Castañeda',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Jorge Carrero Copia',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //VICEPRESIDENTE PPC
            [
                'nombre' => 'Lucía Ledesma',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 8,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'David Vera',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //DIPUTADO PPC
            [
                'nombre' => 'Pablo Alberto Secada Elguera',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Lucia Del Pilar Ledesma Martinez De Cruz',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //SENADO PPC
            [
                'nombre' => 'Karem Teresa Craff Malaga',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Ricardo Santiago Vasquez Laguna',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //PARLAMENTO ANDINO PPC
            [
                'nombre' => 'Jorge Javier Koechlin Von Stein',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Jeffrey Moises Kihien Palza',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //SENADO PPC AMAZONAS
            [
                'nombre' => 'Carlos Ronald Viru Bazan',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Nancy Ruth Mego Torres De Rojas',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 34,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //REGIDOR PROVINCIAL LIMA FRENTE ESPERANZA
            [
                'nombre' => 'Leo Miguel De Paz Lancho',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 21,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'Rosana Milagros Zevallos Vargas',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 21,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            [
                'nombre' => 'David Kuoman Saavedra',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 21,
                'region_id' => 5,
                'provincia_id' => 46,
                'distrito_id' => 464,
                'activo' => true,
            ],
            //REGIDOR DISTRITAL SJL RENOVACION POPULAR
            [
                'nombre' => 'Jessenia Lorena Ricra Hurtado',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 41,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Hector Vidaurre Torres',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 41,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
            [
                'nombre' => 'Efrain Aguilar Pardave',
                'slug' => '',
                'descripcion' => '',
                'foto' => 'http://127.0.0.1:8000/assets/images/sesion/user-1.jpg',
                'partido_id' => 41,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1352,
                'activo' => true,
            ],
        ];

        foreach ($candidatos as $index => $data) {
            Candidato::create([
                'nombre' => $data['nombre'],
                'slug' => Str::slug($data['nombre']),
                'descripcion' => 'Descripción del ' . $data['nombre'],
                'foto' => $data['foto'],
                'video_presentacion' => $faker->boolean(40) ? $faker->url : null,
                'plan_gobierno' => $faker->boolean(40) ? $faker->url : null,
                'partido_id' => $data['partido_id'],
                'plan_id' => rand(1, 3),
                'region_id' => $data['region_id'],
                'provincia_id' => $data['provincia_id'],
                'distrito_id' => $data['distrito_id'],
                'candidato_oficial' => $faker->boolean(80) ? 1 : 0,
                'activo' => $faker->boolean(80) ? 1 : 0,
            ]);
        }

    }
}
