<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CandidatoCargoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $candidatos = [
            [
                'nivel_id' => 1,
                'candidato_id' => 1,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 42,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 2,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 1,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 3,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 8,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 4,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 41,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 5,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 18,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 6,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 2,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 7,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 6,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 8,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 12,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 9,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 43,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 10,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 23,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],

            [
                'nivel_id' => 1,
                'candidato_id' => 11,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 37,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 12,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 35,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 13,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 34,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 14,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 40,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 15,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 3,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 16,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 17,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 17,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 29,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 18,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 22,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 19,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 21,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 20,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 24,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 21,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 38,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 22,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 4,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 23,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 10,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 24,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 25,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 1,
                'candidato_id' => 25,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'partido_id' => 5,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            // ALCALDIA  PROVINCIAL LIMA
            [
                'nivel_id' => 3,
                'candidato_id' => 26,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 20,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 3,
                'candidato_id' => 27,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 38,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 3,
                'candidato_id' => 28,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 21,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 3,
                'candidato_id' => 29,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 14,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 3,
                'candidato_id' => 30,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 18,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 3,
                'candidato_id' => 31,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 1,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 3,
                'candidato_id' => 32,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 41,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 3,
                'candidato_id' => 33,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'partido_id' => 3,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            // ALCALDIA  DISTRITAL SJL
            [
                'nivel_id' => 4,
                'candidato_id' => 34,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => null,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 35,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 6,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 36,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 41,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 37,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 18,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 38,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 37,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 39,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
                'principal' => true,
                'electo' => false,
            ],
            // ALCALDIA  DISTRITAL LA VICTORIA
            [
                'nivel_id' => 4,
                'candidato_id' => 40,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 3,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 41,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 21,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 42,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 4,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 43,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 33,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 4,
                'candidato_id' => 44,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'partido_id' => 41,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
                'principal' => true,
                'electo' => false,
            ],
            // GOBIERNO REGIONAL AYACUCHO
            [
                'nivel_id' => 2,
                'candidato_id' => 45,
                'cargo_id' => 6,
                'eleccion_id' => 2,
                'partido_id' => 30,
                'pais_id' => 1,
                'region_id' => 5,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 2,
                'candidato_id' => 46,
                'cargo_id' => 6,
                'eleccion_id' => 2,
                'partido_id' => 20,
                'pais_id' => 1,
                'region_id' => 5,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 2,
                'candidato_id' => 47,
                'cargo_id' => 6,
                'eleccion_id' => 2,
                'partido_id' => 10,
                'pais_id' => 1,
                'region_id' => 5,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
            [
                'nivel_id' => 2,
                'candidato_id' => 48,
                'cargo_id' => 6,
                'eleccion_id' => 2,
                'partido_id' => 38,
                'pais_id' => 1,
                'region_id' => 5,
                'provincia_id' => null,
                'distrito_id' => null,
                'principal' => true,
                'electo' => false,
            ],
        ];

        foreach ($candidatos as $candidato) {
            DB::table('candidato_cargo')->insert([
                'nivel_id' => $candidato['nivel_id'],
                'candidato_id' => $candidato['candidato_id'],
                'cargo_id' => $candidato['cargo_id'],
                'eleccion_id' => $candidato['eleccion_id'],
                'partido_id' => $candidato['partido_id'],
                'pais_id' => $candidato['pais_id'],
                'region_id' => $candidato['region_id'],
                'provincia_id' => $candidato['provincia_id'],
                'distrito_id' => $candidato['distrito_id'],
                'principal' => $candidato['principal'],
                'electo' => $candidato['electo'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
