<?php

namespace Database\Seeders;

use App\Models\Encuesta;
use Carbon\Carbon;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EncuestaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        $encuestas = [
            [
                'nombre' => 'PRESIDENTE PERU 2026 ENERO',
                'categoria_id' => 1,
                'nivel_id' => 1,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'PRESIDENTE PERU 2026 FEBRERO',
                'categoria_id' => 1,
                'nivel_id' => 1,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'PRESIDENTE PERU 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 1,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'PRESIDENTE PERU 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 1,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'PRESIDENTE PERU 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 1,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'PRESIDENTE PERU 2026 JUNIO',
                'categoria_id' => 1,
                'nivel_id' => 1,
                'cargo_id' => 1,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => null,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'SENADO LIMA PERU 2026 FEBRERO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 3,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'SENADO LIMA PERU 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 3,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'SENADO LIMA PERU 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 3,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'SENADO AYACUCHO PERU 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 3,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 5,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'SENADO AMAZONAS PERU 2026 ENERO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 3,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 1,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'DIPUTADO LIMA PERU 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 4,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'DIPUTADO LIMA PERU 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 4,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'DIPUTADO LIMA PERU 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 4,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'DIPUTADO AYACUCHO PERU 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 4,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 5,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'DIPUTADO LA LIBERTAD PERU 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 4,
                'eleccion_id' => 1,
                'pais_id' => 1,
                'region_id' => 12,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'GOBIERNO REGIONAL LA LIBERTAD PERU 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 6,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 12,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'GOBIERNO REGIONAL AYACUCHO PERU 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 2,
                'cargo_id' => 6,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 5,
                'provincia_id' => null,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 ENERO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 FEBRERO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 JUNIO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 JULIO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA LIMA 2026 AGOSTO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA PROVINCIAL CALLAO 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 129,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA PROVINCIAL CALLAO 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 129,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA AMAZONAS-CHACHAPOYAS 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 1,
                'provincia_id' => 3,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA ANCASH-SANTA 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 3,
                'cargo_id' => 9,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 2,
                'provincia_id' => 25,
                'distrito_id' => null,
            ],
            [
                'nombre' => 'ALCALDIA SAN JUAN DE LURIGANCHO 2026 ENERO',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
            ],
            [
                'nombre' => 'ALCALDIA SAN JUAN DE LURIGANCHO 2026 FEBRERO',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
            ],
            [
                'nombre' => 'ALCALDIA SAN JUAN DE LURIGANCHO 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1369,
            ],
            [
                'nombre' => 'ALCALDIA LA VICTORIA 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
            ],
            [
                'nombre' => 'ALCALDIA LA VICTORIA 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
            ],
            [
                'nombre' => 'ALCALDIA LA VICTORIA 2026 MAYO',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 14,
                'provincia_id' => 135,
                'distrito_id' => 1351,
            ],
            [
                'nombre' => 'ALCALDIA SAN MARTIN-TOCACHE-TOCACHE 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 21,
                'provincia_id' => 183,
                'distrito_id' => 1776,
            ],
            [
                'nombre' => 'ALCALDIA UCAYALI-PURUS-PURUS 2026 MARZO',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 24,
                'provincia_id' => 194,
                'distrito_id' => 1830,
            ],
            [
                'nombre' => 'ALCALDIA UCAYALI-PURUS-PURUS 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 24,
                'provincia_id' => 194,
                'distrito_id' => 1830,
            ],
            [
                'nombre' => 'ALCALDIA UCAYALI-ATALAYA-RAYMONDI 2026 ABRIL',
                'categoria_id' => 1,
                'nivel_id' => 4,
                'cargo_id' => 11,
                'eleccion_id' => 2,
                'pais_id' => 1,
                'region_id' => 24,
                'provincia_id' => 191,
                'distrito_id' => 1817,
            ],
        ];

        foreach ($encuestas as $e) {
            Encuesta::create([
                'nombre' => $e['nombre'],
                'slug' => Str::slug($e['nombre']),
                'descripcion' => $faker->sentence,
                'imagen_url' => null,
                'categoria_id' => $e['categoria_id'],
                'nivel_id' => $e['nivel_id'],
                'cargo_id' => $e['cargo_id'],
                'eleccion_id' => $e['eleccion_id'],
                'pais_id' => $e['pais_id'],
                'region_id' => $e['region_id'],
                'provincia_id' => $e['provincia_id'],
                'distrito_id' => $e['distrito_id'],
                'fecha_inicio' => Carbon::now(),
                'fecha_fin' => Carbon::now()->addDays(30),
                'estado' => 'iniciada',
                'activo' => true,
            ]);
        }
    }
}
