<?php

return [
    'FECHA_CONVOCATORIA_ELECCION_GENERAL' => '2025-01-01',
    'FECHA_CONVOCATORIA_ELECCION_REGIONAL' => '2025-01-01',

    'FECHA_SUFRAGIO_ELECCION_GENERAL' => '2026-01-01',
    'FECHA_SUFRAGIO_ELECCION_REGIONAL' => '2026-01-01',

    'TIPO_ELECCION_GENERAL_ID' => 1,
    'TIPO_ELECCION_REGIONAL_ID' => 2,

    'ELECCION_GENERAL_ID' => 1,
    'ELECCION_REGIONAL_ID' => 2,
];
